repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-merge-conflict
    -   id: check-docstring-first
    -   id: check-added-large-files
-   repo: local
    hooks:
    -   id: pylint
        name: Check with pylint
        entry: pylint
        language: system
        types: [python]
        args:
        - '--fail-under=8'
    -   id: pycodestyle
        name: Check with pycodestyle
        entry: pycodestyle
        language: system
        types: [python]
        args:
        - '--select=E,W'
        - '--max-line-length=120'
        - '--exclude=setup.py'
    -   id: pydocstyle
        name: Check with pydocstyle
        entry: pydocstyle
        language: system
        args:
        - --ignore=D1,D203,D213,D401,D406,D407,D413
