version: "3.3"
networks:
    net:
services:
    database:
        image: user-db
        build:
            context: db
            dockerfile: Dockerfile
        container_name: user-db
        ports:
            - "3001:3306"
        volumes:
            - ./db/storage:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
        networks:
            - net
    app:
        build:
            context: app
            dockerfile: Dockerfile
        container_name: app
        ports: 
            - "3000:3000"
        networks:
            - net
