version: "3.3"
networks:
    net:
services:
    database:
        image: mysql:5.7
        container_name: database
        ports:
            - "3001:3306"
        volumes:
            - ./db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: bolsiyo
            MYSQL_PASSWORD: user_password
            MYSQL_DATABASE: prod
        networks:
            - net
    app:
        build:
            context: app
            dockerfile: Dockerfile
        container_name: app
        ports: 
            - "3000:3000"
        networks:
            - net
