CREATE DATABASE prod;
CREATE DATABASE test;

CREATE USER bolsiyo@%
IDENTIFIED BY 'user_password';
GRANT ALL PRIVILEGES ON DATABASE prod TO  bolsiyo@%;
GRANT ALL PRIVILEGES ON DATABASE test TO  bolsiyo@%;